# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa1f44d56c2c6c0b407008cc3e0fe88b4b27488a2c1b6925db421a6eae5e74dc8fa7bea37e8f14e05091e679efe747fd9e98a6eea8d4254dc82debe88db7b556

test:
  secret_key_base: f11cf6ce8ab47e5c6f92ba61ee35d0ff21700b80b06e660e06b6bd4bb8c52afd5c3d99fdb8be18f2082edb12d83f94bc49c1b9680245f9f5bec109cb3288ad75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
